create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "description" text
);


alter table "public"."events" enable row level security;

create table "public"."occurrences" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "event_id" bigint not null,
    "recurrence_series_id" bigint,
    "starts_on" date,
    "start_time" time without time zone
);


alter table "public"."occurrences" enable row level security;

create table "public"."participations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "occurrence_id" bigint not null,
    "profile_id" uuid not null
);


alter table "public"."participations" enable row level security;

create table "public"."recurrence_series" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "event_id" bigint not null,
    "description" text,
    "frequency" text,
    "interval" bigint,
    "count" bigint,
    "ends_on" date,
    "starts_on" date,
    "by_day" text,
    "by_month" text
);


alter table "public"."recurrence_series" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX ocurrences_pkey ON public.occurrences USING btree (id);

CREATE UNIQUE INDEX participations_pkey ON public.participations USING btree (id);

CREATE UNIQUE INDEX recurrence_series_pkey ON public.recurrence_series USING btree (id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."occurrences" add constraint "ocurrences_pkey" PRIMARY KEY using index "ocurrences_pkey";

alter table "public"."participations" add constraint "participations_pkey" PRIMARY KEY using index "participations_pkey";

alter table "public"."recurrence_series" add constraint "recurrence_series_pkey" PRIMARY KEY using index "recurrence_series_pkey";

alter table "public"."occurrences" add constraint "public_ocurrences_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."occurrences" validate constraint "public_ocurrences_event_id_fkey";

alter table "public"."occurrences" add constraint "public_ocurrences_recurrence_series_id_fkey" FOREIGN KEY (recurrence_series_id) REFERENCES recurrence_series(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."occurrences" validate constraint "public_ocurrences_recurrence_series_id_fkey";

alter table "public"."participations" add constraint "public_participations_ocurrence_id_fkey" FOREIGN KEY (occurrence_id) REFERENCES occurrences(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."participations" validate constraint "public_participations_ocurrence_id_fkey";

alter table "public"."participations" add constraint "public_participations_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."participations" validate constraint "public_participations_profile_id_fkey";

alter table "public"."recurrence_series" add constraint "public_recurrence_series_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recurrence_series" validate constraint "public_recurrence_series_event_id_fkey";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";

grant delete on table "public"."occurrences" to "anon";

grant insert on table "public"."occurrences" to "anon";

grant references on table "public"."occurrences" to "anon";

grant select on table "public"."occurrences" to "anon";

grant trigger on table "public"."occurrences" to "anon";

grant truncate on table "public"."occurrences" to "anon";

grant update on table "public"."occurrences" to "anon";

grant delete on table "public"."occurrences" to "authenticated";

grant insert on table "public"."occurrences" to "authenticated";

grant references on table "public"."occurrences" to "authenticated";

grant select on table "public"."occurrences" to "authenticated";

grant trigger on table "public"."occurrences" to "authenticated";

grant truncate on table "public"."occurrences" to "authenticated";

grant update on table "public"."occurrences" to "authenticated";

grant delete on table "public"."occurrences" to "service_role";

grant insert on table "public"."occurrences" to "service_role";

grant references on table "public"."occurrences" to "service_role";

grant select on table "public"."occurrences" to "service_role";

grant trigger on table "public"."occurrences" to "service_role";

grant truncate on table "public"."occurrences" to "service_role";

grant update on table "public"."occurrences" to "service_role";

grant delete on table "public"."participations" to "anon";

grant insert on table "public"."participations" to "anon";

grant references on table "public"."participations" to "anon";

grant select on table "public"."participations" to "anon";

grant trigger on table "public"."participations" to "anon";

grant truncate on table "public"."participations" to "anon";

grant update on table "public"."participations" to "anon";

grant delete on table "public"."participations" to "authenticated";

grant insert on table "public"."participations" to "authenticated";

grant references on table "public"."participations" to "authenticated";

grant select on table "public"."participations" to "authenticated";

grant trigger on table "public"."participations" to "authenticated";

grant truncate on table "public"."participations" to "authenticated";

grant update on table "public"."participations" to "authenticated";

grant delete on table "public"."participations" to "service_role";

grant insert on table "public"."participations" to "service_role";

grant references on table "public"."participations" to "service_role";

grant select on table "public"."participations" to "service_role";

grant trigger on table "public"."participations" to "service_role";

grant truncate on table "public"."participations" to "service_role";

grant update on table "public"."participations" to "service_role";

grant delete on table "public"."recurrence_series" to "anon";

grant insert on table "public"."recurrence_series" to "anon";

grant references on table "public"."recurrence_series" to "anon";

grant select on table "public"."recurrence_series" to "anon";

grant trigger on table "public"."recurrence_series" to "anon";

grant truncate on table "public"."recurrence_series" to "anon";

grant update on table "public"."recurrence_series" to "anon";

grant delete on table "public"."recurrence_series" to "authenticated";

grant insert on table "public"."recurrence_series" to "authenticated";

grant references on table "public"."recurrence_series" to "authenticated";

grant select on table "public"."recurrence_series" to "authenticated";

grant trigger on table "public"."recurrence_series" to "authenticated";

grant truncate on table "public"."recurrence_series" to "authenticated";

grant update on table "public"."recurrence_series" to "authenticated";

grant delete on table "public"."recurrence_series" to "service_role";

grant insert on table "public"."recurrence_series" to "service_role";

grant references on table "public"."recurrence_series" to "service_role";

grant select on table "public"."recurrence_series" to "service_role";

grant trigger on table "public"."recurrence_series" to "service_role";

grant truncate on table "public"."recurrence_series" to "service_role";

grant update on table "public"."recurrence_series" to "service_role";

create policy "Enable read access for all users"
on "public"."events"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."occurrences"
as permissive
for select
to public
using (true);



